keep_health/health_graph/urls.py
from django.conf.urls import url
from . import views

app_name = 'health_graph'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^api/sensor/pressure/view/(?P<date>[0-9]{4}-[0-1][0-9]-[0-3][0-9])$', views.health_pressure_append, name='pressure'),
    url(r'^api/sensor/pressure/append/$', views.seat_pressure_append, name='pressure_append')
]

keep_health/keep_health/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'health_graph/', include('health_graph.urls')),
]

keep_health/health_graph/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class SeatPressure(models.Model):
    minutes = models.DateTimeField()
    average = models.FloatField()
    seat_count = models.IntegerField()

    def pressure_sensor_graph(self):
        return datetime.datetime.now() - datetime.timedelta(days=1) <= \
                self.created < \
                datetime.datetime.now()

keep_health/health_graph/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, SeatPressure
from django.views.decorators.csrf import csrf_exempt
import datetime
import json
import pytz

class IndexView(generic.ListView):
    template_name = 'health_graph/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'health_graph/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'health_graph/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'health_graph/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('health_graph:results', args=(question.id,)))

@csrf_exempt
def seat_pressure_append(request):
    seat_pressure = None
    try:
        pressure_data = json.loads(request.body)
    except ValueError:
        return Http404("Not data")

    for data in pressure_data:
        timestamp = datetime.datetime.strptime(data['time'], "%Y-%m-%d %H:%M")
        sp = SeatPressure(
            seat_count=int(data['seat_count']),
            average=float(data['average']),
            minutes=timestamp.strftime("%Y-%m-%d %H:%M:00")
        )
        sp.save()

    return HttpResponse('success', status=200)

def health_pressure_append(request, date):
    timestamp = datetime.datetime.strptime(date, "%Y-%m-%d")
    seat_pressure = None

    try:
        sp = SeatPressure.objects
        seat_pressure = sp \
            .filter(minutes__gte=(timestamp).strftime("%Y-%m-%d 00:00:00")) \
            .filter(minutes__lt=(timestamp).strftime("%Y-%m-%d 23:59:59"))
    except (KeyError, SeatPressure.DoesNotExist):
        pass

    pressure_output = []
    for seat in seat_pressure:
        pressure_output.append(
            {
                "time": seat.minutes.astimezone(pytz.timezone("Asia/Tokyo")).strftime("%Y/%m/%d %H:%M:%S"),
                "seat_count": seat.seat_count,
                "average": seat.average,
            }
        )

    return HttpResponse(
        json.dumps(pressure_output),
        content_type='application/json; charset=UTF-8',
        status=200
    )

# Create your views here.

keep_health/health_graph/templates/health_graph/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'health_graph:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

keep_health/health_graph/templates/health_graph/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
<head>
<title>ぼくのおうちの状態</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'health_graph/style.css' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'health_graph/bootstrap-3.3.6-dist/css/bootstrap.css' %}" >
<style type="text/css">

    .border-main {
        border-image: url("{% static 'health_graph/bootstrap-3.3.6-dist/img/border.gif' %}") 20 stretch;
        border-style: solid;
        border-width: 18px;
        border-color: white;
    }

    .space {
        margin: 10px;
    }

    .tekimen-background {
        background: url("{% static 'health_graph/bootstrap-3.3.6-dist/img/background.png' %}");
    }

    .white-background {
        background-color: white;
    }

</style>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

<script type="text/javascript">

window.onload = function() {
    var stage;
    stage = d3.select("#d3graph").append("svg:svg").attr("width", 1300).attr("height", 650);

    var graph_scale = 1300 / 1440;

    var colors = d3.scale.category10();
    var d3Line = d3.svg.line()
        .x(function(d,i){return i * graph_scale;} )
        .y(function(d,i){return (1024 - d) / 1024 * 550});

    var seatcountLine = d3.svg.line()
        .x(function(d,i) { return i * graph_scale; })
        .y(function(d,i) { return (60 - d) * 10; });

    var points = {
        seat_count: new Array(),
        average: new Array(),
        time: new Array()
    };

    // http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d
    var point_colors = {
        seat_count: 1,
        average: 2,
        time: 3
    };

    var select_date = new Date();

    var setdate = function() {
        var dd = new Date("2016/03/25");
        var yy = dd.getYear() + 1900;
        var mm = dd.getMonth() + 1;
        var dd = dd.getDate();

        if (mm < 10) {
            mm = "0" + mm;
        }
        if (dd < 10) {
            dd = "0" + dd;
        }

        return yy + "-" + mm + "-" + dd;
    }

    function zeropad(n) {
        if (n < 10) {
            return "0" + n;
        }
        return n;
    }

    function requestHtml(select_date) {
        points = {
            seat_count: new Array(),
            average: new Array(),
            time: new Array()
        };
        stage.selectAll(".fourtext").remove();
        d3.json("api/sensor/pressure/view/" + select_date, function(error, values) {
            for (var i = 0, min = 0, len = 1440, size = values.length; min < len; min++) {
                if (i >= size) {
                    updateValue(1023.0, 'average');
                    updateValue(60, 'seat_count');
                    if (min % 60 == 0) {
                        timeUpdate(zeropad(parseInt(min / 60)) + ":" + zeropad(min % 60), min);
                    }
                    continue;
                }

                var d = new Date(values[i].time);
                if ((d.getHours() * 60) + d.getMinutes() == min) {
                    updateValue(values[i].seat_count, 'seat_count');
                    updateValue(values[i].average, 'average');

                    i++;
                } else {
                    updateValue(1023.0, 'average');
                    updateValue(60, 'seat_count');
                }
                if (min % 60 == 0) {
                    timeUpdate(zeropad(parseInt(min / 60)) + ":" + zeropad(min % 60), min);
                }
            }
            update('average');
            updateSeatCount('seat_count');
        });
    }

    requestHtml(setdate());
    var select = d3.select("#seat_pressure_date").on("change", function() {
        requestHtml(d3.select("#seat_pressure_date").node().value);
    });

    function timeUpdate(value, i) {
        textUpdate(value, i * graph_scale, 600);
    }

    function textUpdate(value, x, y) {
        stage.append("text").attr("class", "fourtext").attr("x", x).attr("y", y).text(value);
    }

    function updateSeatCount(key) {
        // 削除する
        stage.selectAll("." + key).remove();

        // 描画する
        stage.append("path")
            .attr("d", seatcountLine(points[key]))
            .attr("stroke", colors(point_colors[key]))
            .attr("fill", "none")
            .attr("class", key)
            .attr("opacity", 3);
    }

    function updateValue(value, key) {
        points[key].push(value);

        if(points[key].length > 1440) {
            points[key].shift();
        }
    }

    function update(key) {
        // 削除する
        stage.selectAll("." + key).remove();

        // 描画する
        stage.append("path")
            .attr("d", d3Line(points[key]))
            .attr("stroke", colors(point_colors[key]))
            .attr("fill", "none")
            .attr("class", key)
            .attr("opacity", 3);
    }
};
</script>
</head>
<body class="tekimen-background">
    <div class="container-fluid space border-main">
        <h1>ぼくのおうちの状態</h1>

        <div class="row">
            <div class="col-md-6">
                <h2>指定できる日付</h2>
                    <form>
                        <div class="form-group">
                            <select id="seat_pressure_date" class="form-control">
                                <option value="2016-03-21">2016-03-21</option>
                                <option value="2016-03-22">2016-03-22</option>
                                <option value="2016-03-23">2016-03-23</option>
                                <option value="2016-03-24">2016-03-24</option>
                                <option value="2016-03-25">2016-03-25</option>
                                <option value="2016-03-26">2016-03-26</option>
                            </select>
                        </div>
                    </form>
            </div>
        </div>

        <div class="row">
            <div id="d3graph" class="white-background" style="border:1px solid #FFF; margin-bottom:10px"></div>
        </div>

        <div class="row">
            {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                <li><a href="{% url 'health_graph:detail' question.id %}">{{ question.question_text }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No health are available.</p>
            {% endif %}
        </div>
    </div>
</body>
</html>

keep_health/health_graph/templates/health_graph/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'health_graph:detail' question.id %}">Vote again?</a>